### ISSUE TITLE
datatsetsbug

### ISSUE THREAD

**Issue by zyxcambridge** [LinkSoul-AI/Chinese-Llama-2-7b#30]
██████████████████████████████████████████████████████| 3/3 [01:10<00:00, 23.52s/it]
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Loading data...
Traceback (most recent call last):
  File "/mnt/update/LLM/Chinese-Llama-2-7b/train.py", line 284, in <module>
    train()
  File "/mnt/update/LLM/Chinese-Llama-2-7b/train.py", line 266, in train
    data_module = make_supervised_data_module(tokenizer=tokenizer, data_args=data_args)
  File "/mnt/update/LLM/Chinese-Llama-2-7b/train.py", line 212, in make_supervised_data_module
    train_json = load_json(data_args.data_path, data_args.data_cache_path)
  File "/mnt/update/LLM/Chinese-Llama-2-7b/train.py", line 177, in load_json
    dataset = datasets.load_from_disk(data_path)
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 2229, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory LinkSoul/instruction_merge_set/data is neither a `Dataset` directory nor a `DatasetDict` directory.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:10<00:00, 23.61s/it]
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/mnt/update/LLM/Chinese-Llama-2-7b/train.py", line 284, in <module>
    train()
  File "/mnt/update/LLM/Chinese-Llama-2-7b/train.py", line 266, in train
    data_module = make_supervised_data_module(tokenizer=tokenizer, data_args=data_args)
  File "/mnt/update/LLM/Chinese-Llama-2-7b/train.py", line 212, in make_supervised_data_module
    train_json = load_json(data_args.data_path, data_args.data_cache_path)
  File "/mnt/update/LLM/Chinese-Llama-2-7b/train.py", line 177, in load_json
    dataset = datasets.load_from_disk(data_path)
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 2229, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory LinkSoul/instruction_merge_set/data is neither a `Dataset` directory nor a `DatasetDict` directory.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 542) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0a0+4136153', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-26_15:20:56
  host      : 66b6a7894439
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 543)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-26_15:20:56
  host      : 66b6a7894439
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 542)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
root@66b6a7894439:/mnt/update/LLM/Chinese-Llama-2-7b# 
Session was closed
Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-67-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Introducing Expanded Security Maintenance for Applications.
   Receive updates to over 25,000 software packages with your
   Ubuntu Pro subscription. Free for personal use.

     https://ubuntu.com/pro

Expanded Security Maintenance for Applications is not enabled.

136 updates can be applied immediately.
109 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

1 additional security update can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm

New release '22.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Your Hardware Enablement Stack (HWE) is supported until April 2025.
Last login: Wed Jul 26 23:18:55 2023 from 10.212.134.200
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ cd /mnt/update/LLM/Chinese-Llama-2-7b/
ubuntu@ubuntu:/mnt/update/LLM/Chinese-Llama-2-7b$ ls LinkSoul/instruction_merge_set/data
train-00000-of-00027-04692b5b06f21b0e.parquet  train-00007-of-00027-e38601856637bd61.parquet  train-00014-of-00027-123095573bf091a7.parquet  train-00021-of-00027-1c6ead83e4a4dfdd.parquet
train-00001-of-00027-03d7bc07043b5cb5.parquet  train-00008-of-00027-5f4cbbecf811ce30.parquet  train-00015-of-00027-a7c91e0ecc2115bb.parquet  train-00022-of-00027-f47789f09b8a7db9.parquet
train-00002-of-00027-c8b4df3030bd7169.parquet  train-00009-of-00027-90530ffdaae810a3.parquet  train-00016-of-00027-56ffa4baa93905af.parquet  train-00023-of-00027-8f9121be4df84232.parquet
train-00003-of-00027-d7c820529e005815.parquet  train-00010-of-00027-4fdf7031e88d8028.parquet  train-00017-of-00027-33c1148b5b5ea7c5.parquet  train-00024-of-00027-b63c53350262064a.parquet
train-00004-of-00027-3ed772c5e2220e53.parquet  train-00011-of-00027-949799b5bc21f8ef.parquet  train-00018-of-00027-c644b84627338748.parquet  train-00025-of-00027-5081a2ac78ee617d.parquet
train-00005-of-00027-7d1efa72aeee9a19.parquet  train-00012-of-00027-95782d4e6e50a9c4.parquet  train-00019-of-00027-d128d07b8575c772.parquet  train-00026-of-00027-c24354950ffe850f.parquet
train-00006-of-00027-309b9cab175273c7.parquet  train-00013-of-00027-0c020665db8f865b.parquet  train-00020-of-00027-f15fe94c7d9fa800.parquet
ubuntu@ubuntu:/mnt/update/LLM/Chinese-Llama-2-7b$ docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --rm -it -v /mnt/update:/mnt/update  linksoul/chinese-llama2-chat bash

=============
== PyTorch ==
=============

NVIDIA Release 23.06 (build 63009835)
PyTorch Version 2.1.0a0+4136153

Container image Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2023 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 525.105.17 which has support for CUDA 12.0.  This container
  was built with CUDA 12.1 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[Forward compatibility was attempted on non supported HW (CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE) cuInit()=804]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

root@a31c666f8536:/app# 
root@a31c666f8536:/app# cd /mnt/update/LLM/Chinese-Llama-2-7b/
root@a31c666f8536:/mnt/update/LLM/Chinese-Llama-2-7b# ls
Dockerfile  LinkSoul   V            api.py              chinese-llama-2-7b-4bit.ipynb  example  hf_datasets_cache  llama_flash_attn_monkey_patch.py  train.py
LICENSE     README.md  __pycache__  checkpoints_llama2  chinese-llama-2-7b.ipynb       ggml     infer.py           quantization
root@a31c666f8536:/mnt/update/LLM/Chinese-Llama-2-7b# cd L
bash: cd: L: No such file or directory
root@a31c666f8536:/mnt/update/LLM/Chinese-Llama-2-7b# cd LinkSoul/
root@a31c666f8536:/mnt/update/LLM/Chinese-Llama-2-7b/LinkSoul# ls
Chinese-Llama-2-7b  instruction_merge_set
root@a31c666f8536:/mnt/update/LLM/Chinese-Llama-2-7b/LinkSoul# cd instruction_merge_set/
root@a31c666f8536:/mnt/update/LLM/Chinese-Llama-2-7b/LinkSoul/instruction_merge_set# git branch -a
fatal: detected dubious ownership in repository at '/mnt/update/LLM/Chinese-Llama-2-7b/LinkSoul/instruction_merge_set'
To add an exception for this directory, call:

        git config --global --add safe.directory /mnt/update/LLM/Chinese-Llama-2-7b/LinkSoul/instruction_merge_set
root@a31c666f8536:/mnt/update/LLM/Chinese-Llama-2-7b/LinkSoul/instruction_merge_set# git lfs pull
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
        log
root@a31c666f8536:/mnt/update/LLM/Chinese-Llama-2-7b/LinkSoul/instruction_merge_set#

**Comment by mints7** [comment]
Did you solve it? I'm also having the same issue. 你解决了吗？我也遇到了相同的问题。

**Comment by zhong110020** [comment]
train.py  177行 dataset = datasets.load_from_disk(data_path)
改成dataset = datasets.load_dataset(data_path)
可以解决这报错
