### ISSUE TITLE
chinese-llama-2-7b.ipynb出错求助

### ISSUE THREAD

**Issue by leoring123** [LinkSoul-AI/Chinese-Llama-2-7b#52]
请教执行最后一步!cd Chinese-Llama-2-7b/example/basic-chat && python app.py

Traceback (most recent call last):
  File "app.py", line 6, in <module>
    from model import run
  File "/home/ma-user/work/Chinese-Llama-2-7b/example/basic-chat/model.py", line 21, in <module>
    def get_prompt(message: str, chat_history: list[tuple[str, str]],
TypeError: 'type' object is not subscriptable

这是为什么？chinese-llama-2-7b.ipynb执行到第三部了（环境是pytorch1.8，cuda，V100 32G）

**Comment by zlltmy3631** [comment]
up解决了么
